version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/jwt-auth
      PORT: 3005
    depends_on:
      - mongodb
   
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: Chuchu
      MONGO_INITDB_ROOT_PASSWORD: Bibu3015
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
